/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.unit.nva.model.utils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class UpdatePersonIdentifierTest {


    public static final String APPLICATION_CREATED_AND_INITIALIZED_MESSAGE = "UpdatePersonIdentifier should have been created and initialized";

    @Test void utilConvertsPersonIdentifierWhenSourceAndTargetIsGiven() {
        UpdatePersonIdentifier updatePersonIdentifier = new UpdatePersonIdentifier();
        assertNotNull(updatePersonIdentifier, APPLICATION_CREATED_AND_INITIALIZED_MESSAGE);
    }
}
